name: Deploy Documentation on Release

on:
  workflow_dispatch:

jobs:
  docs:
    uses: scikit-package/release-scripts/blob/main/.github/workflows/_release-docs.yml@v0
    #uses: scikit-package/release-scripts/.github/workflows/_publish-docs-on-release.yml@v0
    with:
      project: tlb6700
      c_extension: false
      headless: false
